"use client";

import { useMemo, useState } from "react";
import * as XLSX from "xlsx";

type Row = Record<string, unknown>;
type AppliedSettings = { feeRate:number; marginRate:number; extraCost:number; roundUnit:number; categoryCode:string; courierCode:string; asPhone:string };
type Product = { productName:string; sellerCode:string; basePrice:number; salePrice:number; stock:number; optionName:string; optionValue:string; imageUrl:string; detailHtml:string; categoryCode:string; shippingFee:number; brand:string; maker:string; originCode:string };

const aliases={
 productName:["상품명","제품명","상품이름","품명","상품 명"],sellerCode:["판매자 상품코드","판매자상품코드","상품코드","자체상품코드","관리코드","품목코드","판매자코드"],
 basePrice:["판매가","판매가격","상품가격","상품 판매가","소비자가","정상가","공급가","공급가격","판매단가","단가","기준가격","원가","매입가","가격"],stock:["재고수량","재고","수량","판매가능수량"],
 optionName:["옵션명","옵션항목","옵션"],optionValue:["옵션값","옵션내용","선택옵션"],imageUrl:["대표이미지","대표이미지URL","이미지URL","이미지","메인이미지"],detailHtml:["상세설명","상세HTML","상품상세","상세페이지"],
 categoryCode:["카테고리코드","카테고리번호","카테고리ID"],shippingFee:["기본배송비","배송비"],brand:["브랜드"],maker:["제조사","제조자"],originCode:["원산지코드","원산지"]
};
const naverHeaders=["판매자 상품코드","카테고리코드","상품명","상품상태","판매가","단위가격 사용여부","표시용량","표시단위","총용량","부가세","관부가세","재고수량","옵션형태","옵션명","옵션값","옵션가","옵션 재고수량","직접입력 옵션","추가상품명","추가상품값","추가상품가","추가상품 재고수량","대표이미지","추가이미지","상세설명","브랜드","제조사","제조일자","유효일자","원산지코드","수입사","복수원산지여부","원산지 직접입력","미성년자 구매","배송비 템플릿코드","배송방법","택배사코드","배송비유형","기본배송비","배송비 결제방식","조건부무료-\n상품판매가 합계","수량별부과-수량","구간별-\n2구간수량","구간별-\n3구간수량","구간별-\n3구간배송비","구간별-\n추가배송비","반품배송비","교환배송비","지역별 차등 배송비","별도설치비","상품정보제공고시 템플릿코드","상품정보제공고시\n품명","상품정보제공고시\n모델명","상품정보제공고시\n인증허가사항","상품정보제공고시\n제조자","A/S 템플릿코드","A/S 전화번호","A/S 안내","판매자특이사항","즉시할인 값\n(기본할인)","즉시할인 단위\n(기본할인)","모바일\n즉시할인 값","모바일\n즉시할인 단위","복수구매할인\n조건 값","복수구매할인\n조건 단위","복수구매할인\n값","복수구매할인\n단위","상품구매시 포인트\n지급 값","상품구매시 포인트\n지급 단위","텍스트리뷰 작성시\n지급 포인트","포토/동영상 리뷰 작성시\n지급 포인트","한달사용 텍스트리뷰\n작성시 지급 포인트","한달사용\n포토/동영상리뷰 작성시 지급 포인트","알림받기동의 고객 리뷰 작성 시 지급 포인트","무이자\n할부 개월","사은품","판매자바코드","구매평 노출여부","구매평\n비노출사유","알림받기 동의 고객 전용 여부","ISBN","ISSN","독립출판","출간일","출판사","글작가","그림작가","번역자명","문화비 소득공제","사이즈\n상품군","사이즈\n사이즈명","사이즈\n상세 사이즈","사이즈 \n모델명"];
const requiredRow=naverHeaders.map(h=>["카테고리코드","상품명","판매가","재고수량","대표이미지","상세설명","원산지코드","택배사코드","A/S 전화번호"].includes(h)?"필수":"비필수");
const groupRow=naverHeaders.map((_,i)=>i===0?"상품 기본정보":i===25?"상품 주요정보":i===34?"배송정보":i===50?"상품정보제공고시":i===55?"A/S, 특이사항":i===59?"할인/혜택정보":i===77?"기타 정보":"");
function cleanKey(v:unknown){return String(v??"").replace(/[\s\n\r_\-()\[\]]/g,"").toLowerCase()} function normalize(v:unknown){return String(v??"").trim()} function numberValue(v:unknown){const n=Number(String(v??"").replace(/,/g,"").replace(/[^0-9.-]/g,""));return Number.isFinite(n)?n:0}
function pick(row:Row,names:string[]){const entries=Object.entries(row);for(const name of names){const t=cleanKey(name);const e=entries.find(([k])=>cleanKey(k)===t);if(e)return e[1]}for(const name of names){const t=cleanKey(name);const e=entries.find(([k])=>cleanKey(k).includes(t)||t.includes(cleanKey(k)));if(e)return e[1]}return ""}
function parseSheet(sheet:XLSX.WorkSheet){const matrix=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,defval:"",raw:false});const candidates=[...aliases.productName,...aliases.basePrice,...aliases.sellerCode,...aliases.stock].map(cleanKey);let bestIndex=0,bestScore=-1;matrix.slice(0,30).forEach((row,index)=>{const score=row.map(cleanKey).filter(Boolean).reduce((s,k)=>s+(candidates.some(c=>k===c||k.includes(c)||c.includes(k))?1:0),0);if(score>bestScore){bestScore=score;bestIndex=index}});const raw=(matrix[bestIndex]??[]).map((v,i)=>normalize(v)||`열${i+1}`);const seen=new Map<string,number>();const headers=raw.map(h=>{const n=(seen.get(h)||0)+1;seen.set(h,n);return n===1?h:`${h}_${n}`});const rows=matrix.slice(bestIndex+1).map(values=>Object.fromEntries(headers.map((h,i)=>[h,values[i]??""]))).filter(r=>Object.values(r).some(v=>normalize(v)!==""));return{rows,headerRow:bestIndex+1}}
function calculatePrice(base:number,s:AppliedSettings){if(base<=0)return 0;const raw=(base+s.extraCost)*(1+s.marginRate/100+s.feeRate/100);return Math.ceil(raw/s.roundUnit)*s.roundUnit}
function toProducts(rows:Row[],s:AppliedSettings):Product[]{return rows.map(row=>{const basePrice=numberValue(pick(row,aliases.basePrice));return{productName:normalize(pick(row,aliases.productName)),sellerCode:normalize(pick(row,aliases.sellerCode)),basePrice,salePrice:calculatePrice(basePrice,s),stock:numberValue(pick(row,aliases.stock))||1,optionName:normalize(pick(row,aliases.optionName)),optionValue:normalize(pick(row,aliases.optionValue)),imageUrl:normalize(pick(row,aliases.imageUrl)),detailHtml:normalize(pick(row,aliases.detailHtml)),categoryCode:s.categoryCode,shippingFee:numberValue(pick(row,aliases.shippingFee)),brand:normalize(pick(row,aliases.brand)),maker:normalize(pick(row,aliases.maker)),originCode:normalize(pick(row,aliases.originCode))}}).filter(p=>p.productName||p.sellerCode)}
function productToNaverRow(p:Product,s:AppliedSettings){const row=Array(naverHeaders.length).fill("");const set=(h:string,v:string|number)=>{const i=naverHeaders.indexOf(h);if(i>=0)row[i]=v};set("판매자 상품코드",p.sellerCode);set("카테고리코드",s.categoryCode);set("상품명",p.productName);set("상품상태","신상품");set("판매가",p.salePrice);set("부가세","과세상품");set("재고수량",p.stock);if(p.optionName&&p.optionValue){set("옵션형태",p.optionName.includes("\n")?"조합형":"단독형");set("옵션명",p.optionName);set("옵션값",p.optionValue)}set("대표이미지",p.imageUrl);set("상세설명",p.detailHtml);set("브랜드",p.brand);set("제조사",p.maker);set("원산지코드",p.originCode);set("복수원산지여부","N");set("미성년자 구매","Y");set("배송방법","택배, 소포, 등기");set("택배사코드",s.courierCode);set("배송비유형",p.shippingFee>0?"유료":"무료");set("기본배송비",p.shippingFee);if(p.shippingFee>0)set("배송비 결제방식","선결제");set("반품배송비",p.shippingFee||3000);set("교환배송비",(p.shippingFee||3000)*2);set("별도설치비","N");set("A/S 전화번호",s.asPhone);set("A/S 안내","상품 문의 및 A/S는 판매자에게 연락해 주세요.");set("구매평 노출여부","Y");set("알림받기 동의 고객 전용 여부","N");return row}

export default function Home(){
 const[feeRate,setFeeRate]=useState(6),[marginRate,setMarginRate]=useState(30),[extraCost,setExtraCost]=useState(0),[roundUnit,setRoundUnit]=useState(100);const[categoryCode,setCategoryCode]=useState(""),[courierCode,setCourierCode]=useState(""),[asPhone,setAsPhone]=useState("");
 const[appliedSettings,setAppliedSettings]=useState<AppliedSettings|null>(null),[sourceRows,setSourceRows]=useState<Row[]>([]),[fileName,setFileName]=useState(""),[status,setStatus]=useState("상품 일괄목록 엑셀을 업로드해 주세요.");
 const products=useMemo(()=>appliedSettings?toProducts(sourceRows,appliedSettings):[],[sourceRows,appliedSettings]);
 async function readFile(file?:File){if(!file)return;setFileName(file.name);setAppliedSettings(null);try{const buffer=await file.arrayBuffer();const workbook=XLSX.read(buffer,{type:"array"});const parsed=parseSheet(workbook.Sheets[workbook.SheetNames[0]]);setSourceRows(parsed.rows);setStatus(`${parsed.rows.length}행을 읽었습니다. 머리글은 ${parsed.headerRow}행에서 찾았습니다. 필수값 입력 후 '위 내용 적용하기'를 눌러 주세요.`)}catch{setSourceRows([]);setStatus("파일을 읽지 못했습니다.")}}
 function applySettings(){if(!sourceRows.length||feeRate<0||marginRate<0)return;if(!categoryCode.trim()||!courierCode.trim()||!asPhone.trim()){setAppliedSettings(null);setStatus("네이버 카테고리코드·택배사코드·A/S 전화번호를 모두 입력해 주세요.");return}const next={feeRate,marginRate,extraCost,roundUnit,categoryCode:categoryCode.trim(),courierCode:courierCode.trim(),asPhone:asPhone.trim()};const preview=toProducts(sourceRows,next);const priced=preview.filter(p=>p.basePrice>0).length;if(!priced){setAppliedSettings(null);setStatus("가격 열을 찾지 못했습니다.");return}setAppliedSettings(next);setStatus(`적용 완료: ${priced}개 상품에 가격·카테고리·택배사·A/S 정보를 반영했습니다.`)}
 function downloadNaver(){if(!products.length||!appliedSettings)return;const dataRows=products.map(p=>productToNaverRow(p,appliedSettings));const sheet=XLSX.utils.aoa_to_sheet([groupRow,naverHeaders,requiredRow,...dataRows]);sheet["!cols"]=naverHeaders.map(h=>({wch:Math.min(Math.max(h.replace(/\n/g,"").length+3,12),28)}));sheet["!rows"]=[{hpt:24},{hpt:46},{hpt:22}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,sheet,"일괄등록");XLSX.writeFile(wb,`postsheet02_네이버스마트스토어_${new Date().toISOString().slice(0,10)}.xlsx`)}
 function resetAll(){setSourceRows([]);setFileName("");setAppliedSettings(null);setStatus("화면 데이터를 비웠습니다.")}
 const invalid=feeRate<0||marginRate<0;const changed=!!appliedSettings&&(appliedSettings.feeRate!==feeRate||appliedSettings.marginRate!==marginRate||appliedSettings.extraCost!==extraCost||appliedSettings.roundUnit!==roundUnit||appliedSettings.categoryCode!==categoryCode.trim()||appliedSettings.courierCode!==courierCode.trim()||appliedSettings.asPhone!==asPhone.trim());
 return <main className="container"><section className="hero"><span className="badge">postsheet02 · 상품 대량등록 변환</span><h1>상품 일괄목록을<br/>네이버 등록 파일로 변환</h1><p>가격과 네이버 필수 등록정보를 일괄 적용한 파일을 생성합니다.</p><div className="privacy">원본·결과 파일 서버 저장 없음 · 브라우저 안에서만 처리</div></section><section className="panel"><div className="field full"><label>1. 상품 일괄목록 엑셀 업로드</label><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>readFile(e.target.files?.[0])}/><small>{fileName||"선택된 파일 없음"}</small></div><div className="field"><label>2. 네이버 수수료율 (%)</label><input min={0} step={0.1} type="number" value={feeRate} onChange={e=>setFeeRate(Number(e.target.value))}/></div><div className="field"><label>3. 추가 마진율 (%)</label><input min={0} step={0.1} type="number" value={marginRate} onChange={e=>setMarginRate(Number(e.target.value))}/></div><div className="field"><label>상품당 추가비용 (원)</label><input min={0} type="number" value={extraCost} onChange={e=>setExtraCost(Number(e.target.value))}/></div><div className="field"><label>판매가 올림 단위</label><select value={roundUnit} onChange={e=>setRoundUnit(Number(e.target.value))}><option value={10}>10원 올림</option><option value={100}>100원 올림</option><option value={500}>500원 올림</option><option value={1000}>1,000원 올림</option></select></div><div className="field"><label>네이버 카테고리코드</label><input value={categoryCode} onChange={e=>setCategoryCode(e.target.value)} placeholder="네이버에서 확인한 카테고리코드"/><small>원본 쇼핑몰 코드는 사용하지 않습니다.</small></div><div className="field"><label>택배사코드</label><input value={courierCode} onChange={e=>setCourierCode(e.target.value)} placeholder="네이버 양식의 택배사코드"/></div><div className="field"><label>A/S 전화번호</label><input value={asPhone} onChange={e=>setAsPhone(e.target.value)} placeholder="예: 031-000-0000"/></div>{changed&&<div className="status full">입력값이 변경됐습니다. 다시 '위 내용 적용하기'를 눌러 주세요.</div>}<div className="actions full"><button onClick={downloadNaver} disabled={!products.length||invalid||changed}>네이버 스마트스토어 파일 다운로드</button><button onClick={applySettings} disabled={!sourceRows.length||invalid}>위 내용 적용하기</button><button className="secondary" onClick={resetAll}>초기화</button></div><div className="status full">{status}</div></section><section className="preview"><div className="previewHead"><h2>가격 계산 미리보기</h2><span>{products.length}개 상품</span></div><div className="tableWrap"><table><thead><tr><th>상품명</th><th>상품코드</th><th>원래 판매가격</th><th>최종 판매가</th><th>카테고리</th></tr></thead><tbody>{products.slice(0,30).map((p,i)=><tr key={`${p.sellerCode}-${i}`}><td>{p.productName}</td><td>{p.sellerCode}</td><td>{p.basePrice.toLocaleString()}</td><td>{p.salePrice.toLocaleString()}</td><td>{appliedSettings?.categoryCode}</td></tr>)}{!products.length&&<tr><td colSpan={5} className="empty">엑셀 업로드 후 필수값을 입력하고 적용해 주세요.</td></tr>}</tbody></table></div></section></main>
}